config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils.translation import ugettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from tuticfruti_blog.posts import views

urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name="home"),

    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # Your stuff: custom urls includes go here
    #CKEditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    # User management
    url(_(r'^users/'), include("tuticfruti_blog.users.urls", namespace="users")),
    url(_(r'^accounts/'), include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(_(r'^posts/'), include('tuticfruti_blog.posts.urls', namespace='posts')), )

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', 'django.views.defaults.bad_request'),
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    ]

tuticfruti_blog/posts/urls.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /posts/
    url(r'^$', views.PostListView.as_view(), name='list'),

    # ex: /posts/post/post-title-0/
    url(_(r'^post/(?P<slug>(?!search)[-\w]+)/$'), views.PostDetailView.as_view(), name='detail'),

    # ex: /posts/post/1/
    url(_(r'^post/(?P<pk>[0-9]+)/$'), views.PostDetailView.as_view(), name='detail_by_pk'),

    # ex: /posts/category/python/
    url(_(r'^category/(?P<slug>[-\w]+)/$'), views.PostListByCategoryView.as_view(), name='list_by_category'),

    # ex: /posts/search/
    url(_(r'^search/$'), views.PostListSearchView.as_view(), name='search'),
    # ex: /posts/category/python/search/
    url(
        _(r'^category/(?P<slug>[-\w]+)/search/$'),
        views.PostListSearchView.as_view(),
        name='search_by_category'),
]

tuticfruti_blog/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

tuticfruti_blog/posts/models.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify

from ckeditor_uploader.fields import RichTextUploadingField

from tuticfruti_blog.posts import managers
from tuticfruti_blog.users.models import User


class Tag(models.Model):
    term = models.CharField(max_length=255, unique=True, verbose_name=_('term'))

    def __str__(self):
        return self.term

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')
        ordering = ['term']


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True, blank=False, verbose_name=_('name'))
    slug = models.SlugField(max_length=100, verbose_name=_('slug'))
    order = models.IntegerField(default=0, verbose_name=_('order'))
    is_enabled = models.BooleanField(default=True, verbose_name=_('is enabled'))

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    objects = managers.CategoryManager()

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')
        ordering = ['order']


class Post(models.Model):
    HR = '<hr />'
    PAGINATE_BY = 10
    PAGINATE_ORPHANS = 1

    STATUS_DRAFT = 'draft'
    STATUS_PUBLISHED = 'published'

    STATUS_CHOICES = (
        (STATUS_DRAFT, _('draft')),
        (STATUS_PUBLISHED, _('published')),
    )

    categories = models.ManyToManyField(Category, related_name='posts', verbose_name=_('categories'))
    author = models.ForeignKey(User, related_name='posts', verbose_name=_('author'))
    title = models.CharField(max_length=255, unique=True, verbose_name=_('title'))
    slug = models.SlugField(max_length=255, db_index=True, verbose_name=_('slug'))
    content = RichTextUploadingField(blank=True, verbose_name=_('content'))
    status_id = models.CharField(
        choices=STATUS_CHOICES,
        default=STATUS_DRAFT,
        max_length=10,
        db_index=True, verbose_name=_('status'))
    tags = models.ManyToManyField(Tag, related_name='posts', verbose_name=_('tags'))
    created = models.DateTimeField(auto_now_add=True, blank=True, db_index=True, verbose_name=_('created'))
    modified = models.DateTimeField(auto_now=True, blank=True, db_index=True, verbose_name=_('modified'))

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

    objects = managers.PostManager()

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')
        ordering = ['-created']


class Comment(models.Model):
    STATUS_PENDING = 'pending'
    STATUS_PUBLISHED = 'published'
    STATUS_CHOICES = (
        (STATUS_PENDING, _('pending')),
        (STATUS_PUBLISHED, _('published')), )

    post = models.ForeignKey(Post, related_name='comments', verbose_name=_('post'))
    status_id = models.CharField(
        choices=STATUS_CHOICES,
        default=STATUS_PENDING,
        max_length=10,
        db_index=True, verbose_name=_('status'))
    author = models.CharField(max_length=100, db_index=True, verbose_name=_('author'))
    email = models.EmailField(db_index=True, verbose_name=_('email'))
    content = models.TextField(verbose_name=_('content'))
    created = models.DateTimeField(auto_now_add=True, blank=True, db_index=True, verbose_name=_('created'))
    modified = models.DateTimeField(auto_now=True, blank=True, db_index=True, verbose_name=_('created'))

    def __str__(self):
        return self.content

    objects = managers.CommentManager()

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')
        ordering = ["-created"]

tuticfruti_blog/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

tuticfruti_blog/posts/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _

from . import models


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['author', 'email', 'content']
        widgets = dict(
            author=forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('Your name')}),
            email=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': _('Your email')}),
            content=forms.Textarea(attrs={'class': 'form-control', 'placeholder': _('Your comment'), 'rows': 2}))

tuticfruti_blog/posts/views.py
# -*- coding: utf-8 -*-
from django.views import generic as generic_views
from django.views.generic import edit as edit_mixins
from django.db.models import Prefetch, Q
from django.core.urlresolvers import reverse

from . import models
from . import forms


class PostListView(generic_views.ListView):
    model = models.Post
    context_object_name = 'posts'
    template_name = 'posts/list.html'
    paginate_by = models.Post.PAGINATE_BY
    paginate_orphans = models.Post.PAGINATE_ORPHANS

    def get_queryset(self):
        categories = models.Category.objects.all_enabled()
        tags = models.Tag.objects.all()
        comments = models.Comment.objects.all_published()

        queryset = models.Post.objects \
            .all_published() \
            .prefetch_related(
                Prefetch('categories', queryset=categories),
                Prefetch('tags', queryset=tags),
                Prefetch('comments', queryset=comments)) \
            .select_related('author')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = models.Category.objects.all_enabled()

        return context


class PostListByCategoryView(PostListView):
    def get_queryset(self):
        queryset = super().get_queryset()
        category_slug = self.kwargs.get('slug')
        if category_slug:
            queryset = queryset.filter(categories__slug=category_slug)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_category'] = self.kwargs.get('slug')

        return context


class PostListSearchView(PostListByCategoryView):
    def get_queryset(self):
        queryset = super().get_queryset()
        terms = self.request.GET.get('search_terms').split()
        regex = r'({})'.format('|'.join(terms))
        queryset = queryset \
            .filter(
                Q(title__iregex=regex) |
                Q(categories__name__iregex=regex) |
                Q(tags__term__iregex=regex)) \
            .distinct()

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_terms'] = self.request.GET.get('search_terms')

        return context


class PostDetailView(edit_mixins.FormMixin, generic_views.DetailView):
    template_name = 'posts/detail.html'
    form_class = forms.CommentForm
    context_object_name = 'post'

    def get_queryset(self):
        categories = models.Category.objects.all_enabled()
        tags = models.Tag.objects.all()
        comments = models.Comment.objects.all_published()

        queryset = models.Post.objects \
            .filter(slug=self.kwargs.get('slug')) \
            .prefetch_related(
                Prefetch('comments', queryset=comments),
                Prefetch('tags', queryset=tags),
                Prefetch('categories', queryset=categories)) \
            .select_related('author')

        return queryset

    def get_success_url(self):
        return reverse('posts:detail', kwargs=dict(slug=self.get_object().slug))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['categories'] = models.Category.objects.all_enabled()

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        models.Comment.objects.create(
            post=self.get_object(),
            author=form['author'].value(),
            email=form['email'].value(),
            content=form['content'].value())

        return super().form_valid(form)

tuticfruti_blog/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

tuticfruti_blog/templates/_categories.html
{% if id == 'categories_id' %}
  <ul id="categories_id" class="nav navbar-nav hidden-sm-down">
    {% for category in categories %}

      {% if category.slug == current_category %}
        <li class="nav-item">
          <a id="category{{ category.pk }}_id" href="#" class="category nav-link active">{{ category.name }}</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a id="category{{ category.pk }}_id" href="{% url 'posts:list_by_category' category.slug %}" class="category nav-link">{{ category.name }}</a>
        </li>
      {% endif %}

    {% endfor %}
  </ul>
{% endif %}

{% if id == 'categories_responsive_id' %}
  <div id="categories_responsive_id" class="list-group listgroup">
    {% for category in categories %}

        {% if category.slug == current_category %}
          <a id="category_responsive{{ category.pk }}_id" href="#" class="category list-group-item active">{{ category.name }}</a>
        {% else %}
          <a id="category_responsive{{ category.pk }}_id" href="{% url 'posts:list_by_category' category.slug %}" class="category list-group-item">{{ category.name }}</a>
        {% endif %}

    {% endfor %}
  </div>
{% endif %}

tuticfruti_blog/templates/_footer.html
{% load i18n %}

<div id="footer_id" class="text-center">
  <h6><em>&copy; {% now "Y" %} Tuticfruti blog.</em></h6>
  <div class="small text-muted">
    <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"></a>
    {% trans 'This work is licensed under a' %} <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
  </div>.
</div>

tuticfruti_blog/templates/_header.html
<nav id="navbar-top" class="navbar navbar-light navbar-fixed-top bg-faded row"> <!-- nav -->
  <div class="col-xs-12 col-sm-7">
    <a class="navbar-brand" href="{% url 'home' %}">Blog</a>
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <a href="{% url "posts:list_category" 'python' %}" class="nav-link {% if current_category_id == 'python' %} active{% endif %}">Python</a>
      </li>
      <li class="nav-item">
        <a href="{% url "posts:list_category" 'django' %}" class="nav-link {% if current_category_id == 'django' %} active{% endif %}">Django</a>
      </li>
      <li class="nav-item">
        <a href="{% url "posts:list_category" 'miscellaneous' %}" class="nav-link {% if current_category_id == 'miscellaneous' %} active{% endif %}">Miscellaneous</a>
      </li>
    </ul>
  </div>
  <div class="col-xs-12 col-sm-5">
    <form id="search_form" action="{% if current_category_id %}{% url 'posts:search_category' current_category_id %}{% else %}{% url 'posts:search' %}{% endif %}" method="get" class="form-inline navbar-form pull-right">
      <div class="input-group">
        <input name="search_terms" type="text" class="form-control" placeholder="Search ..." value="{% if search_terms %}{{ search_terms }}{% endif %}" aria-label="">
        <span class="input-group-btn">
          <button class="btn btn-secondary" type="submit">Go!</button>
        </span>
      </div>
    </form>
  </div>
</nav> <!-- /nav -->

tuticfruti_blog/templates/_navbar_top.html
{% load static %}

<nav id="navbar-top" class="navbar navbar-light navbar-fixed-top bg-faded">

  <div class="row">

    <div class="col-xs-12 hidden-md-up">
      <div class="collapse" id="exCollapsingNavbar">
        <div class="bg-faded p-a">
          <p>{% include '_categories.html' with id='categories_responsive_id' %}</p>
          <p>{% include '_search_form.html' with id='search_form_responsive_id' %}</p>
          <br><br>
        </div> <!-- /list-group -->
      </div>
    </div>

    <div class="col-sm-11 col-md-8">
      <a class="navbar-brand" href="{% url 'home' %}" title="Tuticfruti blog">Tuticfruti blog</a>
      {% include '_categories.html' with id='categories_id' %}
    </div>

    <div class="col-md-4 hidden-sm-down">
      {% include '_search_form.html' with id='search_form_id' %}
    </div>

    <div class="col-sm-1 pull-right hidden-md-up">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
        &#9776;
      </button>
    </div>

  </div>
</nav>

tuticfruti_blog/templates/_pagination.html
{% load i18n %}

{% if is_paginated %}
  <div class="row">
    <div class="col-sm-12">
      <div id="pagination_id" class="row">
        <div class="col-xs-10 col-xs-push-1">
          <nav id="pagination">
            <ul class="pager">

              <!-- Newer posts link -->
              {% if page_obj.has_previous %}
                <li class="pager-prev">
                    <a href="?page={{ page_obj.previous_page_number }}">&larr; {% trans 'Newer posts' %}</a>
                </li>
              {% endif %}

              <!-- Older posts link -->
              {% if page_obj.has_next %}
                <li class="pager-next">
                    <a href="?page={{ page_obj.next_page_number }}">{% trans 'Older posts' %} &rarr;</a>
                </li>
              {% endif %}

            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
{% endif %}

tuticfruti_blog/templates/_results_were_not_found.html
{% load i18n %}

<p class="h6 text-muted bg"><em>{% trans 'Results were not found.' %}</em></p>

tuticfruti_blog/templates/_search_form.html
{% load  i18n %}

<form id="{{ id }}" class="pull-right" action="{% if current_category %}{% url 'posts:search_by_category' current_category %}{% else %}{% url 'posts:search' %}{% endif %}" method="get" class="navbar-form">
  <div class="input-group">
    <input name="search_terms" type="text" class="form-control" placeholder="{% trans 'Search ...' %}" value="{% if search_terms %}{{ search_terms }}{% endif %}" aria-label="">
    <span class="input-group-btn">
      <button class="btn btn-primary" type="submit">Go!</button>
    </span>
  </div>
</form>

tuticfruti_blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Required meta tags always come first -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <!-- Bootstrap CSS block -->
  {% block stylesheet %}
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/project.css" %}">
    <link href="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/styles/' %}{{ CKE_CODESNIPPET_THEME }}.css" rel="stylesheet">
  {% endblock stylesheet %}

  <!-- Page title block -->
  <title>{% block title %}Tuticfruti Blog{% endblock title %}</title>

</head>
<body>

  {% include "_navbar_top.html" %}

  <div class="container">
    {% block content %}{% endblock content %}
  </div>

  {% include "_footer.html" %}

  {% block javascript %}

    <!-- Bootstrap -->
    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>

    <!-- KDEditor code snippets -->
    <script src="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js' %}"></script>
    <script>hljs.initHighlightingOnLoad();</script>

  {% endblock javascript %}

</body>
</html>